# Generated by Django 4.0.6 on 2022-07-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('file', models.FileField(upload_to='data/261cf29d-6677-4568-af43-a44f2cbec12f')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocr.doctype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocr.status')),
                ('tags', models.ManyToManyField(to='ocr.tag')),
            ],
        ),
    ]
