# Generated by Django 4.0.6 on 2022-07-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_document_text_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/45862a36-a996-4664-bdc4-b614d9498e45'),
        ),
    ]
