# Generated by Django 4.0.6 on 2022-07-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_document_filename_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filefolder',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/34d850a6-b9aa-4cf3-ad8f-033ea56c4ce8'),
        ),
    ]
