# Generated by Django 4.0.6 on 2022-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_document_filefolder_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='')),
                ('filename', models.CharField(blank=True, max_length=260, null=True)),
                ('filefolder', models.CharField(blank=True, max_length=36, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/c95933cb-2f7b-4d77-9467-246e1bad42a0'),
        ),
    ]
