# Generated by Django 4.0.6 on 2022-07-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_version_document_date_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/e757a6e2-25f0-4905-aee5-c2954f005d4e'),
        ),
    ]
