# Generated by Django 4.0.6 on 2022-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/88f51fa6-7ec5-4367-bb84-53460bd2d331'),
        ),
    ]
