# Generated by Django 4.0.6 on 2022-07-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_alter_document_date_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/67e1ed45-f60c-4194-b355-ef99dc6bbb81'),
        ),
    ]
