# Generated by Django 4.0.6 on 2022-07-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_alter_document_date_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/e81b90df-8eb2-4321-a8f0-a805205cee64'),
        ),
    ]
