# Generated by Django 4.0.6 on 2022-08-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0010_version_version_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/6f987ef9-3565-422d-8093-d084be415314'),
        ),
    ]
