# Generated by Django 4.2.5 on 2023-09-16 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/7d940579-795a-4549-9804-0646e2126e01'),
        ),
    ]
