# Generated by Django 4.2.5 on 2023-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_document_docdate_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/d6981b09-ff90-40e3-b866-e76ba13ed300'),
        ),
    ]
