# Generated by Django 4.2.5 on 2023-10-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0014_person_alter_document_file_alter_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='resubmission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='data/ffe17231-4523-4f92-82fd-6a53989ffa81'),
        ),
    ]
